version: '3.8'
services:
  app:
    build: ../.
    ports:
      - "8181:8181"
    volumes:
      - ../:/app
    environment:
      - AIR_ENV=development
    depends_on:
      - mysql
    networks:
      - temporal-network      
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: renato
      MYSQL_PASSWORD: secret
    networks:
      - temporal-network      
    ports:
      - "3306:3306"
networks:
  temporal-network:
    driver: bridge
    name: temporal-network